---
apiVersion: v1
kind: Secret
metadata:
  name: elliottwes6-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-deploy/elliottwes6-backend-gitops
